### ISSUE TITLE
Android port compatibility?

### ISSUE THREAD

**Issue by Bent3ndo** [Mr-Wiseguy/N64Recomp#22]
While Windows and Linux are already ports you have focussed on (Majora's Mask for example being released) is this capable of Android porting also for handhelds that are very popular now from Retroid/Anbernic that SM64 Port and Harkinian can work on already?

Thanks :)

**Comment by Azaze7** [comment]
I'm not a developer on this project, but it appears that right now this device can only export .exe files for use in a windows system. However, you can try using a windows emulator to use these ports on a Retroid or other similar handheld, assuming that .apk support doesn't get officially added soon.

I suggest looking into Winlator, which is a windows emulator for android devices. I've used it on my Samsung Galaxy Fold to play Fallout 4 natively on the device. (Not cloud streaming or gamepass, full on windows emulation for x86) There are videos put out about it on YouTube by ETA Prime, who does a ton of testing for emulation devices.

I know these handhelds aren't the most powerful things out there, but since we'd just be running a n64 game compiled explicitly for windows, you should be able to play them on the go and still have all the expanded features like the increased draw distance and better framerate. 

Please let me know if this is something you think is feasible. I could be completely off.

**Comment by Mr-Wiseguy** [comment]
This project outputs C code that can be compiled on any platform. Supporting specific platforms is something a person using this tool would have to do, not something this tool does itself.
